apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::038777382091:role/eksctl-demo-cluster-1-cluster-ServiceRole-81cCxWD7CMiG
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::038777382091:role/service-role/codebuild-webapp-project-dev-service-role
      username: build
      groups:
        - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::038777382091:user/archin
      username: archin
      groups:
        - system:masters



kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system